---
- hosts: all
  become: true
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Add Universe1 Repository
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu eoan main universe
        state: present

    - name: Add Universe2 Repository
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu eoan-security main universe
        state: present

    - name: Add Universe3 Repository
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu eoan-updates main universe
        state: present

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']


    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest


    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "hello-world"
        source: pull

    - name: Insert a line at the end of a file.
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: hey

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: ""
        image: "hello-world"
        command: ""
        state: present

